name: Generate Snake Game
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: shivayapandey
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
